version: "3"
services:
  mongo:
    image: mongo:3.6.19-xenial
    env_file: ${ENV_FILE}
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
